import ReactHotToast from "@/components/react-hot-toast";
import { AbilityProvider } from "@/shared/providers/AbilityProvider";
import ReactQueryProvider from "@/shared/providers/ReactQueryClient";
import ThemeProvider from "@/shared/theme/ThemeProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import Navigation from "@/components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Курс Нейро",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = (await cookies()).get("token");

  return (
    <html lang="ru">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AbilityProvider accessToken={token?.value}>
            <AppRouterCacheProvider>
              <ThemeProvider>
                <Navigation />
                {children}
                <ReactHotToast>
                  <Toaster
                    position="top-right"
                    toastOptions={{ className: "react-hot-toast", style: { zIndex: 9999 } }}
                  />
                </ReactHotToast>
              </ThemeProvider>
            </AppRouterCacheProvider>
          </AbilityProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
